/* Automatically generated by './build/bin/build-entry.js' */

import MoreDialog from '../packages/moreDialog/index.js';
import TopViewMenu from '../packages/topViewMenu/index.js';
import CollapseTransition from 'evenpowerui/src/transitions/collapse-transition.js';

const components = [
  MoreDialog,
  TopViewMenu,
  CollapseTransition
]

const install = function(Vue, opts = {}) {
  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$moreDialog = MoreDialog;
}

/* 支持使用标签的方式引入 */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.5',
  install,
  CollapseTransition,
    MoreDialog,
  TopViewMenu
}
